Feat/new theme
alfa-laboratory/arui-feather pull request #1239
Opened 2020-12-16 14:15 UTC by FenkoAlex

В вебвью мобайла приходит темная тема, поэтому обновляем компоненты на темную/светлую тему

Эта ветка будет корневой для обновления,
дополнительно будем мержиться сюда.
после первой итерации (как наработаем побольше компонентов) планируем слиться в мастер

2020-12-17 08:06 UTC, aso1datov commented on src/spin/spin.css
> +.spin_theme_alfa-dark {
nit: Кажется, можно просто совместить с `.spin_theme_alfa-on-color`

```css
.spin_theme_alfa-on-color,
.spin_theme_alfa-dark {
    ...
```

2020-12-17 08:16 UTC, aso1datov commented on src/vars.css
> +/* @import "@alfalab/core-components/vars/colors-bluetint.css"; */
```suggestion
```

2020-12-17 08:23 UTC, ethorz commented on src/link/link.css
> +.lint_theme_alfa-light {
Кажется, что тут опечатка

2020-12-17 08:26 UTC, ethorz requested changes

2020-12-17 08:26 UTC, ethorz commented on src/link/link.css
> +.lint_theme_alfa-light {
.link_theme_alfa-light {

2020-12-17 08:29 UTC, ethorz requested changes

2020-12-17 08:29 UTC, ethorz commented on src/link/link.css
> +.lint_theme_alfa-light {
.lint_theme_alfa-light {

2020-12-17 08:31 UTC, ethorz commented on src/link/link.css
> +.lint_theme_alfa-light {
```suggestion
.link_theme_alfa-light {
```

2020-12-17 09:59 UTC, FenkoAlex commented on src/spin/spin.css
> +.spin_theme_alfa-dark {
поправил, спасибо

2020-12-17 09:59 UTC, FenkoAlex commented on src/vars.css
> +/* @import "@alfalab/core-components/vars/colors-bluetint.css"; */
поправил, спасибо

2020-12-17 09:59 UTC, FenkoAlex commented on src/link/link.css
> +.lint_theme_alfa-light {
поправил, спасибо

2020-12-22 11:18 UTC, ethorz commented on src/input/input_theme_alfa-dark.css
> +@import "~@alfalab/core-components-vars/colors-bluetint.css";
```suggestion
@import "@alfalab/core-components-vars/colors-bluetint.css";
```

2020-12-22 11:18 UTC, ethorz commented on src/input/input_theme_alfa-light.css
> +@import "~@alfalab/core-components-vars/colors-bluetint.css";
```suggestion
@import "@alfalab/core-components-vars/colors-bluetint.css";
```

2020-12-23 07:16 UTC, FenkoAlex commented on src/input/input_theme_alfa-dark.css
> +@import "~@alfalab/core-components-vars/colors-bluetint.css";
спасибо, не заметил

2021-05-27 08:41 UTC, reabiliti approved these changes

2021-05-27 08:57 UTC, avkvak approved these changes

2021-05-27 09:28 UTC, merged